apps/cf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('admin/', admin.site.urls),
]

apps/store/urls.py
from django.urls import path

from . import views

app_name = "store"


urlpatterns = [
    path("", views.IndexTemplateView.as_view(), name="index"),
    path("new-search/", views.SearchCreateView.as_view(), name="new-search"),
    path(
        "new-land-register/",
        views.LandRegisterCreateView.as_view(),
        name="new-land-register",
    ),
    path(
        "new-instrument/",
        views.InstrumentCreateView.as_view(),
        name="new-instrument",
    ),
    path(
        "order-list/",
        views.OrderListView.as_view(),
        name="order-list",
    ),
    path(
        "cashier-list/",
        views.CashierListView.as_view(),
        name="cashier-list",
    ),
    path(
        "mark-as-paid/<int:pk>/",
        views.mark_as_paid,
        name="mark-as-paid",
    ),
    path(
        "vault-list/",
        views.VaultListView.as_view(),
        name="vault-list",
    ),
    path(
        "mark-as-printed/<int:pk>/",
        views.mark_as_printed,
        name="mark-as-printed",
    ),
    path(
        "secretary-list/",
        views.SecretaryListView.as_view(),
        name="secretary-list",
    ),
    path(
        "mark-as-stamped/<int:pk>/",
        views.mark_as_stamped,
        name="mark-as-stamped",
    ),
    path(
        "deliveries-list/",
        views.DeliveriesListView.as_view(),
        name="deliveries-list",
    ),
    path(
        "mark-as-delivered/<int:pk>/",
        views.mark_as_delivered,
        name="mark-as-delivered",
    ),
]

apps/store/models.py
from django.db import models
from django.urls import reverse

STATUS_LIST = [
    ("payment pending", "payment pending"),
    ("searching", "searching"),
    ("printed", "printed"),
    ("stamped", "stamped"),
    ("delivered", "delivered"),
]

SEARCH_LIST = [
    ("search", "search"),
    ("land register", "land register"),
    ("instrument", "instrument"),
]


class Store(models.Model):
    status = models.CharField(
        max_length=25,
        choices=STATUS_LIST,
        default="payment pending",
    )
    search = models.CharField(max_length=20, choices=SEARCH_LIST, null=True)
    ticket = models.CharField(max_length=3, null=True)
    block = models.CharField(max_length=20, null=True, blank=True)
    parcel = models.CharField(max_length=20, null=True, blank=True)
    name = models.CharField(max_length=20, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ["ticket"]

    def mark_as_paid(self):
        return reverse("store:mark-as-paid", args=[str(self.pk)])

    def mark_as_printed(self):
        return reverse("store:mark-as-printed", args=[str(self.pk)])

    def mark_as_stamped(self):
        return reverse("store:mark-as-stamped", args=[str(self.pk)])

    def mark_as_delivered(self):
        return reverse("store:mark-as-delivered", args=[str(self.pk)])

    def __str__(self):
        return str(self.ticket)

apps/store/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView, UpdateView
from django.views.generic.edit import UpdateView

from .models import Store


class IndexTemplateView(TemplateView):
    template_name = "index.html"


class SearchCreateView(SuccessMessageMixin, CreateView):
    model = Store
    fields = [
        "ticket",
        "name",
        "block",
        "parcel",
    ]
    success_url = "/"
    success_message = "order# %(ticket)s was created"

    def form_valid(self, form):
        form.instance.search = 'search'
        return super().form_valid(form)


class LandRegisterCreateView(SuccessMessageMixin, CreateView):
    model = Store
    fields = [
        "ticket",
        "block",
        "parcel",
    ]
    success_url = "/"
    success_message = "order# %(ticket)s was created"

    def form_valid(self, form):
        form.instance.search = "land register"
        return super().form_valid(form)


class InstrumentCreateView(SuccessMessageMixin, CreateView):
    model = Store
    fields = [
        "ticket",
        "block",
        "parcel",
    ]
    success_url = "/"
    success_message = "order# %(ticket)s was created"

    def form_valid(self, form):
        form.instance.search = "instrument"
        return super().form_valid(form)


class OrderListView(ListView):
    model = Store
    queryset = Store.objects.filter(
        Q(status="payment pending")
        | Q(status="searching")
        | Q(status="stamped")
        | Q(status="printed")
    )
    ordering = ["-updated"]
    template_name = "store/order_list.html"


class CashierListView(ListView):
    model = Store
    queryset = Store.objects.filter(
        Q(status="payment pending") | Q(status="stamped")
    )
    template_name = "store/cashier_list.html"
    ordering = ["-updated"]


def mark_as_paid(request, pk):
    order_item = Store.objects.get(pk=pk)
    order_item.status = "searching"
    order_item.save()
    return redirect("store:cashier-list")


def mark_as_delivered(request, pk):
    delivered_item = Store.objects.get(pk=pk)
    delivered_item.status = "delivered"
    delivered_item.save()
    return redirect("store:cashier-list")


class VaultListView(ListView):
    model = Store
    queryset = Store.objects.filter(status="searching")
    ordering = ["updated"]
    template_name = "store/vault_list.html"


def mark_as_printed(request, pk):
    vault_item = Store.objects.get(pk=pk)
    vault_item.status = "printed"
    vault_item.save()
    return redirect("store:vault-list")


class SecretaryListView(ListView):
    model = Store
    queryset = Store.objects.filter(status="printed")
    ordering = ["updated"]
    template_name = "store/secretary_list.html"


def mark_as_stamped(request, pk):
    secretary_item = Store.objects.get(pk=pk)
    secretary_item.status = "stamped"
    secretary_item.save()
    return redirect("store:secretary-list")


class DeliveriesListView(ListView):
    model = Store
    queryset = Store.objects.filter(status="delivered")
    ordering = ["-updated"]
    template_name = "store/delivered_list.html"

apps/store/templates/store/cashier_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Cashier
{% endblock title %}


{% block content %}

<div class="container small">

    {% for object in object_list %}

    {% if object.status == 'payment pending' %}
    <div class="alert alert-primary shadow"
        data-bs-toggle="collapse"
        href="#collapseExample{{object.pk}}"
        role="button"
        aria-expanded="false"
        aria-controls="collapseExample{{object.pk}}"
        role="alert">

        {% elif object.status == 'stamped' %}
        <div class="alert alert-secondary shadow"
            data-bs-toggle="collapse"
            href="#collapseExample{{object.pk}}"
            role="button"
            aria-expanded="false"
            aria-controls="collapseExample{{object.pk}}"
            role="alert">
            {% endif %}
            order#
            {{ object.ticket }}
            <span>({{object.status }}...)</span>
            <span>updated: {{object.updated|naturaltime}}</span>
            <div class="collapse"
                id="collapseExample{{object.pk}}">
                {% if object.status == 'payment pending' %}

                <form action="{{ object.mark_as_paid }}"
                    method="post">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-success"
                        type="submit">mark as paid</button>
                </form>


                {% elif object.status == 'stamped' %}

                <form action="{{ object.mark_as_delivered }}"
                    method="post">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-success"
                        type="submit">mark as delivered</button>
                </form>
                {% endif %}

            </div>

        </div>
        {% empty %}
        <div class="text-center">
            <h3>no orders as yet</h3>
        </div>
        {% endfor %}
    </div>

    {% endblock content %}

apps/store/templates/store/delivered_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Deliveries
{% endblock title %}


{% block content %}

<div class="container small">

    {% for object in object_list %}

    {% if object.status == 'delivered' %}
    <div class="alert alert-warning shadow"
        data-bs-toggle="collapse"
        href="#collapseExample{{object.pk}}"
        role="button"
        aria-expanded="false"
        aria-controls="collapseExample{{object.pk}}"
        role="alert">
            {% endif %}
            order#
            {{ object.ticket }}
            <span>({{object.status }}...)</span>
            <span>updated: {{object.updated|naturaltime}}</span>
            <div class="collapse"
                id="collapseExample{{object.pk}}">
                {% if object.status == 'printed' %}

                <form action="{{ object.mark_as_stamped }}"
                    method="post">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-success"
                        type="submit">mark as stamped</button>
                </form>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>

    {% endblock content %}

apps/store/templates/store/order_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Orders
{% endblock title %}


{% block content %}

<div class="container small">

    {% for object in object_list %}

    {% if object.status == 'payment pending' %}
    <div class="alert alert-primary shadow"
        role="alert">

        {% elif object.status == 'searching' %}
        <div class="alert alert-warning shadow"
            role="alert">

            {% elif object.status == 'printed' %}

            <div class="alert alert-info shadow"
                role="alert">

                {% elif object.status == 'delivered' %}

                <div class="alert alert-success shadow"
                    role="alert">

                    {% elif object.status == 'stamped' %}
                    <div class="alert alert-secondary shadow"
                        role="alert">
                        {% endif %}
                        order#
                        {{ object.ticket }}
                        <span>({{object.status }}...)</span>
                        <span>updated: {{object.updated|naturaltime}}</span>

                    </div>
                    {% empty %}
                    <div class="text-center">
                        <h3>no orders as yet</h3>
                    </div>

                    {% endfor %}
                </div>

                {% endblock content %}

apps/store/templates/store/secretary_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Secretary
{% endblock title %}


{% block content %}

<div class="container small">

    {% for object in object_list %}

    {% if object.status == 'printed' %}
    <div class="alert alert-warning shadow"
        data-bs-toggle="collapse"
        href="#collapseExample{{object.pk}}"
        role="button"
        aria-expanded="false"
        aria-controls="collapseExample{{object.pk}}"
        role="alert">
        {% endif %}
        order#
        {{ object.ticket }}
        <span>({{object.status }}...)</span>
        <span>updated: {{object.updated|naturaltime}}</span>
        <div class="collapse"
            id="collapseExample{{object.pk}}">
            {% if object.status == 'printed' %}

            <form action="{{ object.mark_as_stamped }}"
                method="post">
                {% csrf_token %}
                <button class="btn btn-sm btn-success"
                    type="submit">mark as stamped</button>
            </form>


            {% elif object.status == 'printed' %}


            {% endif %}

        </div>

    </div>

    {% empty %}
    <div class="text-center"
        role="">
        <h3>no orders as yet</h3>
    </div>

    {% endfor %}
</div>

{% endblock content %}

apps/store/templates/store/store_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block title %}
New Search
{% endblock title %}]


{% block content %}
<div class="container">
    <h2>New Search</h2>
    <div class="col-4">
        <form action=""
        method="post">
        {% csrf_token %}
    
        {{form|crispy }}
        <div class="d-grid gap-2 mx-auto">
        <button class="btn btn-success mt-3" type="submit">send to cashier</button>
        </div>
    </form>
    </div>
    <div class="col">

    </div>
</div>

{% endblock content %}

apps/store/templates/store/vault_list.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
Vault
{% endblock title %}


{% block content %}

<div class="container small">

    {% for object in object_list %}

    {% if object.status == 'searching' %}
    <div class="alert alert-warning shadow"
        data-bs-toggle="collapse"
        href="#collapseExample{{object.pk}}"
        role="button"
        aria-expanded="false"
        aria-controls="collapseExample{{object.pk}}"
        role="alert">
        {% endif %}
        order#
        {{ object.ticket }}
        <span>({{object.status }}...)</span>
        <span>updated: {{object.updated|naturaltime}}</span>
        <div class="collapse"
            id="collapseExample{{object.pk}}">
            {% if object.status == 'searching' %}
            <div class="container my-3">
                {% if object.search %}
                <li>Search: {{ object.search|upper }}</li>
                {% endif %}
                {% if object.name %}
                <li>Name: {{ object.name }}</li>
                {% endif %}
                {% if object.block %}
                <li>Block: {{ object.block }}</li>
                {% endif %}
                {% if object.parcel %}
                <li>Parcel: {{ object.parcel }}</li>
                {% endif %}
            </div>
            <form action="{{ object.mark_as_printed }}"
                method="post">
                {% csrf_token %}
                <button class="btn btn-sm btn-success"
                    type="submit">mark as printed</button>
            </form>



            {% endif %}

        </div>

    </div>
    {% empty %}
    <div class="text-center"
        role="">
        <h3>no orders as yet</h3>
    </div>

    {% endfor %}
</div>

{% endblock content %}

apps/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
        crossorigin="anonymous">

    <link rel="preconnect"
        href="https://fonts.gstatic.com">
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap"
        rel="stylesheet">

    <link rel="shortcut icon"
        href="{% static 'img/coat.jpg' %}"
        type="image/x-icon">

    <style>
        body {
            font-family: 'Montserrat', sans-serif;
        }

        #alert-message {
            z-index: 99;
            position: absolute;
            right: 2%;
            top: 10%;
            opacity: 1;
            transition: opacity 500ms;
        }

        #alert-message-1 {
            opacity: 1;
            transition: display 500ms;
        }

        .waa {
            display: 0;
        }
    </style>

    <title>

        {% block title %}

        {% endblock title %}
        - Land Registry
    </title>
</head>

<body>
    {% include 'info-bar.html' %}

    {% include 'header.html' %}

    {% include 'messages.html' %}



    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

    <script>
        setTimeout(function () {
            document.getElementById('alert-message').className = 'waa';
        }, 5000);
        var message_ele = document.getElementById("alert-message-1");

        setTimeout(function () {
            message_ele.style.display = "none";
        }, 5000);
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
</body>

</html>

apps/templates/header.html
<header
  class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-body border-bottom shadow mx-auto">
  <nav class="my-2 my-md-0 me-md-3">
    <a class="p-2 text-dark text-decoration-none"
      href="{% url 'store:index' %}">Reception</a>
    <a class="p-2 text-dark text-decoration-none"
      href="{% url 'store:order-list' %}">Orders</a>
    <a class="p-2 text-dark text-decoration-none"
      href="{% url 'store:cashier-list' %}">Cashier</a>
    <a class="p-2 text-dark text-decoration-none"
      href="{% url 'store:vault-list' %}">Vault</a>
    <a class="p-2 text-dark text-decoration-none"
      href="{% url 'store:secretary-list' %}">Secretary</a>
    <a class="p-2 text-dark text-decoration-none"
      href="{% url 'store:deliveries-list' %}">Deliveries</a>
  </nav>
</header>

apps/templates/index.html
{% extends 'base.html' %}


{% block title %}
Reception
{% endblock title %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col">

            <a class="text-decoration-none text-light"
                href="{% url 'store:new-search' %}">
                <div class="card text-white bg-success mb-3"
                    style="max-width: 18rem;">
                    <div class="card-header"></div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Search</h5>

                    </div>
                </div>
            </a>
        </div>
        <div class="col">

            <a class="text-decoration-none text-light"
                href="{% url 'store:new-land-register' %}">
                <div class="card text-white bg-primary mb-3"
                    style="max-width: 18rem;">
                    <div class="card-header"></div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Land Register</h5>

                    </div>
                </div>
            </a>
        </div>
        <div class="col">

            <a class="text-decoration-none text-light"
                href="{% url 'store:new-instrument' %}">
                <div class="card text-white bg-warning mb-3"
                    style="max-width: 18rem;">
                    <div class="card-header"></div>
                    <div class="card-body">
                        <h5 class="card-title text-center">Instrument</h5>

                    </div>
                </div>
            </a>
        </div>

    </div>
</div>

{% endblock content %}

apps/templates/info-bar.html
{% load store_tags %}

<div class="mt-auto py-1 bg-light">
    <div class="container text-center">
        <span class="text-muted">{% orders_delivered %} of {% total_orders %} orders delivered</span>
    </div>
</div>

apps/templates/messages.html
{% if messages %}

<div class="container mt-3">
    {% for message in messages %}
    {% if message.tags %}
    <div id="alert-message"
        class="alert alert-{{ message.tags }} show shadow-lg mb-5 rounded alert-message"
        role="alert">
        {% endif %}
        <strong id="alert-message-1">{{ message }}</strong>
        {% endfor %}
    </div>
{% endif %}